### ISSUE TITLE
Mejora:  parametrizar el tamaño del dado

### ISSUE THREAD

**Issue by MeLlamoPablo** [AdryDev92/ultimateroletoolbox#1]
Buenas! Te propongo una serie de mejoras, y hago una issue para cada una para no mezclar cosas y que resulte más fácil.

La primera: actualmente tienes una función para cada dado (D4, D6, D8, D10, D12, D20), tal que así:

```js
function diceD4() {
    var numRandom = Math.floor(Math.random()* 4+1);
    var box = document.getElementById("D4");
    box.value = numRandom;
}
function diceD6() {

    var numRandom2 = Math.floor(Math.random()* 6+1);
    var box2 = document.getElementById("D6");
    box2.value = numRandom2;
}
function diceD8(){

    var numRandom3 = Math.floor(Math.random()* 8+1);
    var box3 = document.getElementById("D8");
    box3.value = numRandom3;
}
function diceD10() {

    var numRandom4 = Math.floor(Math.random()* 10+1);
    var box4 = document.getElementById("D10");
    box4.value = numRandom4;
}
function diceD12() {

    var numRandom5 = Math.floor(Math.random()* 12+1);
    var box5 = document.getElementById("D12");
    box5.value = numRandom5;
}
function diceD20() {

    var numRandom6 = Math.floor(Math.random()* 20+1);
    var box6 = document.getElementById("D20");
    box6.value = numRandom6;
}
```

Imagínate que ahora quires hacer un cambio. Por ejemplo, si el número es mayor o igual que la mitad del dado (Por ejemplo, si es el dado de 12, pues si es mayor o igual que 6), que el fondo del input se ponga verde. Si no, que se ponga rojo. Sería un poco coñazo, porque tendrías que modificar las seis funciones. Y si tuvieras diez dados mas, pues tendrías que hacer el cambio dieciséis veces.

Una solución mucho más fácil es tener una sola función para todo. Y en tu input pondrías algo así:

```html
<!-- En vez de esto... -->
<input type="button" onclick="diceD4();" value="D4" style="width:40px;">

<!-- Tendríamos esto... -->
<input type="button" onclick="dice(4);" value="D4" style="width:40px;">
```

En el atributo `onclick` de los elementos html puedes pasar parámetros si quieres. Y nuestra función nos quedaría así:

```js
function dice(longitudDado) {
    // ...
}
```

Lo único que nos faltaría serían dos cosas:

* Cambiar el `Math.random()` para que genere el número según el parámentro, y
* referenciar al input correcto según el parámetro.

Lo primero es muy sencillo:

```js
// Antes
var numRandom = Math.floor(Math.random()* 4+1);

// Después
var numRandom = Math.floor(Math.random()* longitudDado +1);
```

Lo segundo parece más rallante, pero no es nada del otro mundo:

```js
// Antes
var box = document.getElementById("D4");

// Después
var box = document.getElementById("D" + numRandom);
```
Y al final el código quedaría así:

```js
function dice(longitudDado) {
    var numRandom = Math.floor(Math.random()* longitudDado +1);
    var box = document.getElementById("D" + longitudDado);
    box.value = numRandom;
}
```

Ahora si quieres modificarlo, todo lo que hagas en esa función se aplicará a todos los dados, en vez de tener que ir funcion por función :ok_hand:

Por otra parte (aunque no esté relacionado), es mejor usar `let` en vez de `var`. [Aquí tienes una explicación](http://stackoverflow.com/a/11444416). El único motivo por el que es mejor usar `var` es por que funciona en todos los navegadores. `let` es parte de ES6 (La nueva versión de JS) y no funciona en los antiguos. [Aquí](http://caniuse.com/#feat=let) tienes una tabla de compatibilidad. Funciona en las últimas versiones de casi todo así que no hay que preocuparse. Pero si en un trabajo te toca programar para Internet Explorer 6... Hay que joderse.

**Comment by AdryDev92** [comment]
Dados parametrizados en el siguiente commit: 2c5d7187dd833be18bac84de2e806755c9e77c2d
